#!/bin/bash

appids="luneta"
appdir=$(pwd)

if [[ -z $1 ]]; then
    echo "Error : command need additional paramater"
fi

if [[ $1 == "--install" ]];then
    /bin/bash $appdir/library/installs --purge &&
    exit
fi

if [[ $1 == "--reset" ]];then
    /bin/bash /bin/bash $appdir/library/installs &&
    exit
fi


if [[ $1 == "--build" ]];then
   /bin/bash $appdir/library/build &&
   exit
fi

if [[ $1 == "--deploy" ]];then
    /bin/bash $appdir/library/deploy &&
    exit
fi

if [[ $1 == "--getapp" ]];then
    /bin/bash $appdir/library/getpkg $appdir &&
    exit
fi

if [[ $1 == "--update" ]];then
    /bin/bash $appdir/library/repoup &&
    exit
fi