#!/bin/bash

appids="luneta"
appdir=/install/scripts
reldir=$(pwd)

if [[ -z $1 ]]; then
    echo "Error : $appids command need additional paramater"
fi

if [[ $1 == "--install" ]];then
    /bin/bash $appdir/library/installs $appids &&
    exit
fi

if [[ $1 == "--build" ]];then
   /bin/bash $appdir/library/build $appids &&
   exit
fi

if [[ $1 == "--deploy" ]];then
    /bin/bash $appdir/library/deploy $appids &&
    exit
fi

if [[ $1 == "--reset" ]];then
    /bin/bash $appdir/library/reseter $appids &&
    exit
fi

if [[ $1 == "--getapp" ]];then
    /bin/bash $(pwd)/scripts/library/getpkg $reldir $appids &&
    exit
fi

if [[ $1 == "--update" ]];then
    echo "pull repository" && git pull && 
    echo "populating file" && git add . &&
    echo "commit  changes" && git commit -m "$(date)" &&
    echo "push to gitrepo" && git push &&
    exit
fi